# ===========================
# Server Settings
# ===========================
server.port=8080

# ===========================
# DataSource Settings (MySQL)一旦仮置き　
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/oversession?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


